CREATE TABLE [dbo].[Employee]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[EmployeeNumber] [int] NOT NULL DEFAULT 0,
	[Identification] [varchar](25) NULL ,	
	[Name] [varchar](100) NOT NULL ,
	[FirstLastName] [varchar](100) NULL ,
    [SecondLastName] [varchar](100) NOT NULL ,
	[FullName] [varchar](100) NOT NULL ,
    [Gender] [int] NOT NULL DEFAULT 1 ,
	[MaritalStatus] [int] NOT NULL DEFAULT 1,
	[Dependents] [int] NOT NULL DEFAULT 0 ,
	[BirthDate] [datetime] NULL ,
	[StartDate] [datetime] NULL ,
	[EndDate] [datetime] NULL,
	[EndReason] [varchar](500) NULL ,
	[Nationality] [varchar](100)  NULL ,
	[Detail] [varchar](500) NULL ,
	[PrimaryPhoneNumber] [varchar](25)  NULL,
	[SecundaryPhoneNumber] [varchar](25) NULL ,
	[EmergencyPhoneNumber] [varchar](25)  NULL,
	[EmergencyContact] [varchar](100) NULL,
	[PersonalEmail] [varchar](100)  NULL,
	[NotificationsEmail] [varchar](100) NOT  NULL ,
	[Schooling] [int]  NOT NULL DEFAULT 1 ,
	[Country] [int] NOT NULL ,
	[State] [int]  NOT NULL,
	[City] [int]  NOT NULL,
	[District] [int]  NOT NULL ,
	[Address] [varchar](500) NULL,
	[Picture] [varchar](100) NULL,
	[HasPassport] [bit]  NOT NULL DEFAULT 0 ,
	[PassportNumber] [varchar](100)  NULL ,
	[PassportIssueCity] [int] NULL ,
	[PassportExpeditionDate] [datetime] NULL ,
	[PassportExpirationDate] [datetime] NULL ,
	[HasVisa] [bit] NOT NULL DEFAULT 0 ,
	[VisaNumber] [varchar](100)  NULL,
	[VisaIssueCity] [int]  NULL,
	[VisaExpeditionDate] [datetime] NULL ,
	[VisaExpirationDate] [datetime]  NULL,
	[HasLicense] [bit] NOT NULL DEFAULT 0 ,
	[LicenseNumber] [varchar](100)  NULL,
	[LicenseExpeditionDate] [datetime] NULL ,
	[LicenseExpirationDate] [datetime]  NULL,
	[Enabled] [bit]  NOT NULL DEFAULT 1 ,
	[CreatedBy] [varchar](25)  NOT NULL,
	[CreatedDate] [datetime]   NOT NULL,
	[EditedBy] [varchar](25)  NULL,
	[EditedDate] [datetime]  NULL,
    CONSTRAINT [Pk_Employee] PRIMARY KEY (Id),
	CONSTRAINT [Fk_Employee_Country] FOREIGN KEY([Country]) REFERENCES [dbo].[Country] ([Id]),
	CONSTRAINT [Fk_Employee_State] FOREIGN KEY([State]) REFERENCES [dbo].[State] ([Id]),
	CONSTRAINT [Fk_Employee_City] FOREIGN KEY([City])	REFERENCES [dbo].[City] ([Id]),
	CONSTRAINT [Fk_Employee_District] FOREIGN KEY([District]) REFERENCES [dbo].[District] ([Id]),
	CONSTRAINT [Fk_Employee_User] FOREIGN KEY([UserId]) REFERENCES [dbo].[User] ([Id])	
);
