//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proximity.HR.Data
{
    using System;
    
    public partial class EmpTeachFeat
    {
        public short Employee { get; set; }
        public short Feature { get; set; }
        public bool Teachable { get; set; }
        public bool Desirable { get; set; }
        public string Detail { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public short Level { get; set; }
    }
}
